### ISSUE TITLE
Plural example add documentation

### ISSUE THREAD

**Issue by AdrienEtienne** [Aller-Couleur/handlebars-i18n#45]
Hi,

I am not sure if I am using it the wrong way. But I cant have the plural example working.
Everything else is working great as much I can tell.

So maybe the documentation needs to be more explicit on how to use it?

My npm modules are : 
```json
    "handlebars": "^4.7.7",
    "handlebars-i18n": "^1.5.0",
```

Is plurals working for you?

**Comment by fwalzel** [comment]
Thanks for realizing this. i18next changed its specs from JSON v2 to v3 recently [see here](https://www.i18next.com/misc/json-format#i18next-json-v2). I added the param { compatibilityJSON: 'v2' }  in handlebars-i18n v1.5.1 to the examples. Should work when you update handlebars-i18n in your npm modules to latest version.

**Comment by AdrienEtienne** [comment]
Ok great. The version 1.5.1 fixed that
